language: python
python:
 - "3.5"
install: 
 - "pip install -r requirements.txt"
 - "pip install coveralls"
env:
 - COVERAGE_FILE=".coverage"
script: coverage run --source=flask_app/app -m unittest discover flask_app/test
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=X6JdJ0hDMlzKhHIAi5NTG9ZUEkEw01PB2
after_success:
  coveralls
